
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SteveDelezioSEAssignment2Sit1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_Users
{

    public tbl_Users()
    {

        this.tbl_Articles = new HashSet<tbl_Articles>();

        this.tbl_StateWorkflows = new HashSet<tbl_StateWorkflows>();

    }


    public int UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string Surname { get; set; }

    public int RoleId { get; set; }



    public virtual ICollection<tbl_Articles> tbl_Articles { get; set; }

    public virtual tbl_Roles tbl_Roles { get; set; }

    public virtual ICollection<tbl_StateWorkflows> tbl_StateWorkflows { get; set; }

}

}
