
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SteveDelezioSEAssignment2Sit1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_Articles
{

    public int ArticleId { get; set; }

    public string ArticleTitle { get; set; }

    public string ArticleContent { get; set; }

    public string ArticleComments { get; set; }

    public System.DateTime ArticlePublishDateTime { get; set; }

    public int UserId { get; set; }

    public int ArticleMediaManagerId { get; set; }

    public int ArticleStatusId { get; set; }

    public int ArticleStateId { get; set; }



    public virtual tbl_Users tbl_Users { get; set; }

    public virtual tbl_ArticleStatuses tbl_ArticleStatuses { get; set; }

    public virtual tbl_ArticleStates tbl_ArticleStates { get; set; }

}

}
