//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteveDelezioSEAssignment2Sit1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_Users
    {
        public tbl_Users()
        {
            this.tbl_Articles = new HashSet<tbl_Articles>();
        }
    
        public int UserId { get; set; }

        [Display(Name = "Username")]
        [Required]
        public string Username { get; set; }

        [DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Surname")]
        public string Surname { get; set; }

        [Required]
       
        public int RoleId { get; set; }
    
        public virtual ICollection<tbl_Articles> tbl_Articles { get; set; }
         [Display(Name = "Role")]
        public virtual tbl_Roles tbl_Roles { get; set; }
    }
}
