//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteveDelezioSEAssignment2Sit1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArticleStates
    {
        public tbl_ArticleStates()
        {
            this.tbl_Articles = new HashSet<tbl_Articles>();
            this.tbl_StateWorkflows = new HashSet<tbl_StateWorkflows>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<tbl_Articles> tbl_Articles { get; set; }
        public virtual ICollection<tbl_StateWorkflows> tbl_StateWorkflows { get; set; }
    }
}
