//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SteveDelezioSEAssignment2Sit1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StateWorkflows
    {
        [Range(1, 4)]
        public int WorflowPositionId { get; set; }
        public int UserId { get; set; }
        public int StateId { get; set; }
        public int StateWorkflow_Id { get; set; }
    
        public virtual tbl_ArticleStates tbl_ArticleStates { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
